name: Test Manual Trigger 2

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'A random value for test'
        required: true

jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Print Input
        run: |
          echo "Test input value: ${{ github.event.inputs.test_input }}"